### ISSUE TITLE
How do you ensure fair data usage?

### ISSUE THREAD

**Issue by ZhangGongjie** [YoungXIAO13/FewShotDetection#18]
You created 2 datasets. One is meta dataset (support dataset). The other one is training dataset. Both datasets have been filtered to contain only K number of training samples for novel categories. (K is from K-shot)

However, I don't find the codes to ensure that the samples from meta dataset and training dataset are exactly the same. If both datasets are mutually exclusive, then the total number of training samples used shall be 2x the correct number.

Please kindly correct me if I am missing something here. Thank you very much! @YoungXIAO13

**Comment by YoungXIAO13** [comment]
Hi @ZhangGongjie ,

Actually, the training dataset in the few-shot fine-tuning stage uses exactly the same training samples as meta dataset. For example, the VOC data loader in the second stage initialises from [voc_2007_shots](https://github.com/YoungXIAO13/FewShotDetection/blob/a2290077782dae9946c9d8501b50f53f169f6fa6/train.py#L194), which is generated in the [meta dataset](https://github.com/YoungXIAO13/FewShotDetection/blob/a2290077782dae9946c9d8501b50f53f169f6fa6/lib/datasets/metadata.py#L44).

Using this configuration, the meta dataset and the training dataset share the same samples, thus K for K-shot.

**Comment by ZhangGongjie** [comment]
Thank you so much for your clarification!

One more issue, could you please clarify whether K-shot means K bounding box(es) for each novel category, or K image(s) for each category (in this case, object instances may be larger than K)?

**Comment by YoungXIAO13** [comment]
Sure, the number of samples represents the number of objects (or the bounding boxes).
In the meta dataset, the [number of K](https://github.com/YoungXIAO13/FewShotDetection/blob/a2290077782dae9946c9d8501b50f53f169f6fa6/lib/datasets/metadata.py#L108) is increased each time an instance is added.

**Comment by ZhangGongjie** [comment]
an image can contain multiple bbox of multiple categories. How do you ensure that the number of each category is exactly K? Simply by discarding some of the annotations?

**Comment by YoungXIAO13** [comment]
This sampling strategy is initially proposed in [Meta R-CNN](https://github.com/yanxp/MetaR-CNN), where the annotations beyond K are simply discarded. This is also used in a more recent paper [TFA](https://github.com/ucbdrive/few-shot-object-detection/blob/6b0769b5d682fbf7fdcdaed0c1d0dfd51c373468/datasets/prepare_voc_few_shot.py#L64)

Personally I think that this is not the perfect sampling strategy for few-shot object detection since it would potentially create some false negative in the GT, but I followed this for a direct comparison when I was pushing on this project. You can surly try a different sampling strategy as long as you keep the number of annotated instance as K for each novel category.

**Comment by ZhangGongjie** [comment]
Thanks for your clarification. Thank you so much!
