### ISSUE TITLE
Some packages in spec-file.txt don't exist

### ISSUE THREAD

**Issue by hzhupku** [YoungXIAO13/FewShotDetection#2]
CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/backports.weakref-1.0rc1-py36_0.tar.bz2>
Elapsed: 00:00.636837
CF-RAY: 5ba4566f1fe00ba4-HKG

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/html5lib-0.9999999-py36_0.tar.bz2>
Elapsed: 00:00.521513
CF-RAY: 5ba45672bd1d1995-HKG

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/bleach-1.5.0-py36_0.tar.bz2>
Elapsed: 00:00.504550
CF-RAY: 5ba4567608961923-HKG

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/tensorflow-gpu-base-1.3.0-py36cuda8.0cudnn6.0_1.tar.bz2>
Elapsed: 00:00.522496
CF-RAY: 5ba4567938783291-HKG

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/anaconda/linux-64/tensorflow-gpu-1.3.0-0.tar.bz2>
Elapsed: 00:00.570590
CF-RAY: 5ba4567c7cda0bcc-HKG

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

**Comment by YoungXIAO13** [comment]
Hi,
I just tested it on Ubuntu 14.04 and 16.04, both work fine for me. Maybe some packages in the spec-file.txt are out of date for your environments because of compiler/conda version of sth else.

I think you can just comment the lines of packages that went wrong and re-install the virtual env (you can also use venv with pip install). The most important thing is that you install the **correct pytorch version** (I tried on **0.4.0**, not sure about version higher than it) and correctly **compile the cuda files in ``lib/``**.

**Comment by hzhupku** [comment]
Thank you for your reply. I just install the right torch and torchvision and install others when required. It works.
