### ISSUE TITLE
About metadata.py.

### ISSUE THREAD

**Issue by hzhupku** [YoungXIAO13/FewShotDetection#4]
1. in metadata.py, if phase==2, shots=shots*3. I don't understand why shots*3. Is this will cause an unfair performance comparison?

2. about metaclass, when finetuning, why specify all_classes_first/second/third, is these three the same? Does the order matter?

**Comment by YoungXIAO13** [comment]
1. In the second phase, **shots*3** objects per class are created for each class. However, a [roidb filter](https://github.com/YoungXIAO13/FewShotDetection/blob/dc329a114f4aebe00390b511d023b0208924c839/train.py#L274) is used to make sure there are only **shots** objects kept for each novel class. This is an operation borrowed from Meta R-CNN.

2. The class order actually matters for the [evaluation](https://github.com/YoungXIAO13/FewShotDetection/blob/dc329a114f4aebe00390b511d023b0208924c839/lib/datasets/pascal_voc.py#L280) since we needs a class structure like **[base_classes, novel_classes]** for reporting respectively the performance on base and novel classes.

**Comment by hzhupku** [comment]
Thank you for your reply.
